name: Composite action referring to action in repo folder

on:
  workflow_dispatch:

jobs:
  composite_action_job:
    runs-on: ubuntu-latest
    steps:
      - name: First composite action step
        id: compositeaction
        uses: harukine/actions-composite-action/compositeaction@v1
        with:
          your-name: 'TestName'

      - name: Check directory
        run: ls
